server:
  port: ${PORT}

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Flyway migrations
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Kafka configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: identity-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topics:
      - workspace.created
      - workspace.membership.deleted

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.admin.base-url}/realms/${keycloak.admin.realm}
      client:
        registration:
          identity-service:
            provider: keycloak
            client-id: ${keycloak.admin.client-id}
            client-secret: ${keycloak.admin.client-secret}
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
        provider:
          keycloak:
            issuer-uri: ${keycloak.admin.base-url}/realms/${keycloak.admin.realm}

keycloak:
  admin:
    base-url: ${KEYCLOAK_BASE_URI}
    realm: ${KEYCLOAK_ENVIRONMENT}
    client-id: identity-service
    client-secret: ${IDENTITY_SERVICE_CLIENT_SECRET}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: DEBUG
    com.mochafund.identityservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info